# coding: utf-8

"""
    kubeResource

    Manage Resources from k8s

    OpenAPI spec version: 1.0.0
    Contact: jonathan@saharacluster.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kube_resource
from kube_resource.rest import ApiException
from kube_resource.models.v1_preconditions import V1Preconditions


class TestV1Preconditions(unittest.TestCase):
    """ V1Preconditions unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1Preconditions(self):
        """
        Test V1Preconditions
        """
        model = kube_resource.models.v1_preconditions.V1Preconditions()


if __name__ == '__main__':
    unittest.main()
