# coding: utf-8

"""
    kubeResource

    Manage Resources from k8s

    OpenAPI spec version: 1.0.0
    Contact: jonathan@saharacluster.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_apis_fqdn_v1_namespaces_namespace_resource_name_get(self):
        """
        Test case for apis_fqdn_v1_namespaces_namespace_resource_name_get

        Gets a specific Resource
        """
        pass

    def test_apis_fqdn_v1_resource_get(self):
        """
        Test case for apis_fqdn_v1_resource_get

        Gets Resources
        """
        pass


if __name__ == '__main__':
    unittest.main()
