swagger: "2.0"

info:
  version: 1.0.0
  title: kubeResource
  description: Manage Resources from k8s
  contact:
    name: Jonathan Kosgei
    email: jonathan@saharacluster.com
schemes:
  - https
host: kubernetes.default.svc
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /apis/{fqdn}/v1/{resource}:
    get:
      security:
        - Bearer: []
      summary: Gets Resources
      description: Returns a list of Resources
      parameters:
        - name: watch
          uniqueItems: true
          type: boolean
          description: Watch for changes to the described resources and return them as a stream
            of add, update, and remove notifications. Specify resourceVersion.
          in: query
        - name: fqdn
          in: path
          required: true
          description: The Third party Resource fqdn
          type: string
        - name: resource
          in: path
          required: true
          description: The Resource type
          type: string
      responses:
        200:
          description: A list of Resources
          schema:
            type: object
    post:
      security:
        - Bearer: []
      summary: Create a Resource
      description: Creates a third party resource of the type specified
      parameters:
        - name: fqdn
          in: path
          required: true
          description: The Third party Resource fqdn
          type: string
        - name: resource
          in: path
          required: true
          description: The Resource type
          type: string
        - name: body
          in: body
          required: true
          description: The JSON schema of the Resource to create.
          schema:
            type: object
      responses:
        201:
          description: A list of Resources
          schema:
            type: object
  /apis/{fqdn}/v1/namespaces/{namespace}/{resource}/{name}:
    get:
      security:
        - Bearer: []
      summary: Gets a specific Resource
      description: Returns a specific Resource in a namespace
      parameters:
        - name: namespace
          in: path
          required: true
          description: The Resource's namespace
          type: string
        - name: name
          in: path
          required: true
          description: The Resource's name
          type: string
        - name: fqdn
          in: path
          required: true
          description: The Third party Resource fqdn
          type: string
        - name: resource
          in: path
          required: true
          description: The Resource type
          type: string
      responses:
        200:
          description: A single Resource
          schema:
            type: object