# coding: utf-8

"""
    kubeResource

    Manage Resources from k8s

    OpenAPI spec version: 1.0.0
    Contact: jonathan@saharacluster.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .v1_delete_options import V1DeleteOptions
from .v1_preconditions import V1Preconditions
